### PR TITLE
#181151222 Link Pivotal Tracker to GitHub

### PR DESCRIPTION
**Pull request by semitalatimothy**
#### What does this PR do?

- This PR links Pivotal Tracker to Github

#### Description of Task to be completed?

- When a commit message is made for a story, it changes the status of that story in Pivotal Tracker
#### How should this be manually tested?

- By checking the status of a story in Pivotal Tracker

#### Any background context you want to provide?
- No
#### What are the relevant pivotal tracker stories?

- https://www.pivotaltracker.com/story/show/181151222

#### Screenshots (if appropriate)
image
image

#### Questions:

- None

### CODE REVIEW

**Review by Victoria129 — COMMENTED** [review]
Not sure how to test this PR. I see GitHub under integrations in Pivotal Tracker, but I do not see any other GitHub relations other than that. It does not reflect the changes on GitHub.

**Review by Daniel-Kigozi — APPROVED** [review]
Works well

**Review by bogerepau — APPROVED** [review]
LGTM

**Comment by semitalatimothy** [comment]
> Not sure how to test this PR. I see GitHub under integrations in Pivotal Tracker, but I do not see any other GitHub relations other than that. It does not reflect the changes on GitHub.

Please check the details of stories.

**Review by Emmanuel-Dominic — APPROVED** [review]

**Pull request merged**
