### PR TITLE
#181151221 Link Github to Slack

### PR DESCRIPTION
**Pull request by bogerepau**
#### What does this PR do?
- This PR links Github to slack
#### Description of Task to be completed?
- Changes done on Github repo to be received through notifications on the slack channel 
#### How should this be manually tested?
- Make any change on the pull request, commit etc .
#### Any background context you want to provide?
- No
#### What are the relevant pivotal tracker stories?
- None
#### Screenshots (if appropriate)
github notification on slack

#### Questions: 
- None

[start #181151221]

### CODE REVIEW

**Review by semitalatimothy — APPROVED** [review]
Works well

**Review by Victoria129 — APPROVED** [review]
Pull requests on GitHub appear in the "space-invictus" channel that Paul created in Slack.

**Comment by Emmanuel-Dominic** [comment]
@bogerepau, LGT but please add a screenshot to this pull request before I merge it.
Thanks

**Review by Emmanuel-Dominic — APPROVED** [review]
@bogerepau, LGTM but please add a pivotal tracker store link plus a screenshot for the task to this pull request before I merge it.
Thanks

**Review by Daniel-Kigozi — APPROVED** [review]

**Pull request closed without merging**
