### PR TITLE
#181151221 link pivotal tracker to slack

### PR DESCRIPTION
**Pull request by Daniel-Kigozi**
1. What does this PR do?

- This PR links Pivotal Tracker to Slack

2. Description of Task to be completed?

- Integration involves connecting pivatol tracker to the organisations slack account and linking it to a specific channel

3. How should this be manually tested?

- By entering a story into pivotal tracker using bootcamp channel

Any background context you want to provide?
-No

What are the relevant pivotal tracker stories?

- https://www.pivotaltracker.com/story/show/181151221

Screenshots (if appropriate)

Screenshot from 2022-02-11 11-24-18

Questions:
None
[Start #181151221]

### CODE REVIEW

**Review by semitalatimothy — APPROVED** [review]
Stories added in the space-invictus channel can reflect in Pivotal Tracker

**Comment by bogerepau** [comment]
LGTM

**Review by bogerepau — APPROVED** [review]

**Review by Emmanuel-Dominic — COMMENTED** [review]
Please, use the right pull request conventions about the title [link](https://github.com/Emmanuel-Dominic/developer-best-practices/wiki/Git-naming-conventions-and-best-practices)!! and also provide a clear description plus a screenshot about your task.

**Review by Victoria129 — APPROVED** [review]
Pivotal Tracker appears in the slack Space Invictus channel.

**Pull request merged**
