### PR TITLE
#181151231 unit tests for all functionality

### PR DESCRIPTION
**Pull request by Daniel-Kigozi**
What does this PR do?
- This PR tests code functionality in the project

Description of Task to be completed?
- The task requires to write tests that test the views, urls and models in the project

How should this be manually tested?
- Run python manage.py test

Any background context you want to provide?
- No

What are the relevant pivotal tracker stories?
- https://www.pivotaltracker.com/n/projects/2552983/stories/181151231

Screenshots (if appropriate)
image

Questions:
- None

[start #181151231]

### CODE REVIEW

**Comment by bogerepau** [comment]
Test are running well, LGTM.

**Review by bogerepau — APPROVED** [review]

**Review by Emmanuel-Dominic — DISMISSED** [review]
Revise your pull request commit message and we only need to see the test files under your pull request and may be the URL updated file but not the virtualenv files.

**Review by semitalatimothy — APPROVED** [review]

**Comment by bogerepau** [comment]
Tests are running well

**Review by Victoria129 — APPROVED** [review]

**Review by Emmanuel-Dominic — APPROVED** [review]
LGTM

**Pull request merged**
