### PR TITLE
#181151226 Integrate CircleCI with readme badge

### PR DESCRIPTION
**Pull request by Victoria129**
####  What does this PR do?
- This PR intergrates CircleCI with readme badge.

####  Description of Task to be completed?
- Create a status badge for the project with CircleCI.

####  How should this be manually tested?
- By clicking on the status badge in the readme file.

####  Any background context you want to provide?
- No

####  What are the relevant pivotal tracker stories?
- https://www.pivotaltracker.com/story/show/181151226

####  Screenshots (if appropriate)
image
image

####  Questions:
- None

### CODE REVIEW

**Review by Emmanuel-Dominic — DISMISSED** [review]
Rebase, only changes from one file are required here and also review your configurations to run the tests because the work of the circle-ci is to ensure nothing is breaking through running the tests.

**Review by Daniel-Kigozi — APPROVED** [review]
Its working well

**Review by semitalatimothy — APPROVED** [review]

**Comment by bogerepau** [comment]
Looks good to me

**Review by bogerepau — APPROVED** [review]

**Review by Emmanuel-Dominic — APPROVED** [review]
LGTM

**Pull request merged**
